// Code generated by MockGen. DO NOT EDIT.
// Source: update_task.go
//
// Generated by this command:
//
//	mockgen -source=update_task.go -destination=../../mock/usecase/output/mock_update_task.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdateTaskOutputPort is a mock of UpdateTaskOutputPort interface.
type MockUpdateTaskOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateTaskOutputPortMockRecorder
	isgomock struct{}
}

// MockUpdateTaskOutputPortMockRecorder is the mock recorder for MockUpdateTaskOutputPort.
type MockUpdateTaskOutputPortMockRecorder struct {
	mock *MockUpdateTaskOutputPort
}

// NewMockUpdateTaskOutputPort creates a new mock instance.
func NewMockUpdateTaskOutputPort(ctrl *gomock.Controller) *MockUpdateTaskOutputPort {
	mock := &MockUpdateTaskOutputPort{ctrl: ctrl}
	mock.recorder = &MockUpdateTaskOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateTaskOutputPort) EXPECT() *MockUpdateTaskOutputPortMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockUpdateTaskOutputPort) Render() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Render")
}

// Render indicates an expected call of Render.
func (mr *MockUpdateTaskOutputPortMockRecorder) Render() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockUpdateTaskOutputPort)(nil).Render))
}

// RenderError mocks base method.
func (m *MockUpdateTaskOutputPort) RenderError(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderError", err)
}

// RenderError indicates an expected call of RenderError.
func (mr *MockUpdateTaskOutputPortMockRecorder) RenderError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderError", reflect.TypeOf((*MockUpdateTaskOutputPort)(nil).RenderError), err)
}
