// Code generated by MockGen. DO NOT EDIT.
// Source: delete_task.go
//
// Generated by this command:
//
//	mockgen -source=delete_task.go -destination=../../mock/usecase/output/mock_delete_task.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteTaskOutputPort is a mock of DeleteTaskOutputPort interface.
type MockDeleteTaskOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTaskOutputPortMockRecorder
	isgomock struct{}
}

// MockDeleteTaskOutputPortMockRecorder is the mock recorder for MockDeleteTaskOutputPort.
type MockDeleteTaskOutputPortMockRecorder struct {
	mock *MockDeleteTaskOutputPort
}

// NewMockDeleteTaskOutputPort creates a new mock instance.
func NewMockDeleteTaskOutputPort(ctrl *gomock.Controller) *MockDeleteTaskOutputPort {
	mock := &MockDeleteTaskOutputPort{ctrl: ctrl}
	mock.recorder = &MockDeleteTaskOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTaskOutputPort) EXPECT() *MockDeleteTaskOutputPortMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockDeleteTaskOutputPort) Render() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Render")
}

// Render indicates an expected call of Render.
func (mr *MockDeleteTaskOutputPortMockRecorder) Render() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockDeleteTaskOutputPort)(nil).Render))
}

// RenderError mocks base method.
func (m *MockDeleteTaskOutputPort) RenderError(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderError", err)
}

// RenderError indicates an expected call of RenderError.
func (mr *MockDeleteTaskOutputPortMockRecorder) RenderError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderError", reflect.TypeOf((*MockDeleteTaskOutputPort)(nil).RenderError), err)
}
